### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by alterechtschreibung** [thorinii/PacAndroid#2]
How can this be build?

**Comment by thorinii** [comment]
It's a Netbeans project, but requires some setup to get working. As I'm currently working on https://github.com/ThorinII/balloon-box , I'm not able to work on it right now. I plan to return to PacAndroid and fix it/finish it when Balloon Box is done.

In the meantime, I'll keep this issue open to remind me to fix the build... (btw I'd really like to convert it to Maven - I'll see about that later though)

**Comment by thorinii** [comment]
I've converted it to Gradle. See https://github.com/thorinii/pacandroid-gradle.
